-- MySQL Script generated by MySQL Workbench
-- mié 19 abr 2023 09:43:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bgaribaldi709
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bgaribaldi709
-- -----------------------------------------------------

USE `bgaribaldi709` ;

-- -----------------------------------------------------
-- Table `bgaribaldi709`.`FEDERACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bgaribaldi709`.`FEDERACION` (
  `nombre` VARCHAR(45) NOT NULL,
  `fecha` INT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bgaribaldi709`.`CLUB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bgaribaldi709`.`CLUB` (
  `nombre` VARCHAR(45) NOT NULL,
  `num_socios` INT NULL,
  `FEDERACION_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre`),
  INDEX `fk_CLUB_FEDERACION_idx` (`FEDERACION_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_CLUB_FEDERACION`
    FOREIGN KEY (`FEDERACION_nombre`)
    REFERENCES `bgaribaldi709`.`FEDERACION` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bgaribaldi709`.`FECHA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bgaribaldi709`.`FECHA` (
  `fecha` INT NOT NULL,
  PRIMARY KEY (`fecha`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bgaribaldi709`.`PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bgaribaldi709`.`PERSONA` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `fecha_nacimiento` INT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bgaribaldi709`.`CONTRATO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bgaribaldi709`.`CONTRATO` (
  `nom_club` VARCHAR(45) NULL,
  `importe` FLOAT NULL,
  `fecha_baja` INT NULL,
  `FECHA_fecha` INT NOT NULL,
  `CLUB_nombre` VARCHAR(45) NOT NULL,
  `PERSONA_codigo` INT NOT NULL,
  PRIMARY KEY (`PERSONA_codigo`, `CLUB_nombre`),
  INDEX `fk_CONTRATO_FECHA1_idx` (`FECHA_fecha` ASC) VISIBLE,
  INDEX `fk_CONTRATO_CLUB1_idx` (`CLUB_nombre` ASC) VISIBLE,
  INDEX `fk_CONTRATO_PERSONA1_idx` (`PERSONA_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_CONTRATO_FECHA1`
    FOREIGN KEY (`FECHA_fecha`)
    REFERENCES `bgaribaldi709`.`FECHA` (`fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CONTRATO_CLUB1`
    FOREIGN KEY (`CLUB_nombre`)
    REFERENCES `bgaribaldi709`.`CLUB` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CONTRATO_PERSONA1`
    FOREIGN KEY (`PERSONA_codigo`)
    REFERENCES `bgaribaldi709`.`PERSONA` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bgaribaldi709`.`OFERTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bgaribaldi709`.`OFERTA` (
  `importe_oferta` FLOAT NULL,
  `CLUB_nombre` VARCHAR(45) NOT NULL,
  `FECHA_fecha` INT NOT NULL,
  `PERSONA_codigo` INT NOT NULL,
  PRIMARY KEY (`PERSONA_codigo`, `FECHA_fecha`, `CLUB_nombre`),
  INDEX `fk_OFERTA_CLUB1_idx` (`CLUB_nombre` ASC) VISIBLE,
  INDEX `fk_OFERTA_FECHA1_idx` (`FECHA_fecha` ASC) VISIBLE,
  INDEX `fk_OFERTA_PERSONA1_idx` (`PERSONA_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_OFERTA_CLUB1`
    FOREIGN KEY (`CLUB_nombre`)
    REFERENCES `bgaribaldi709`.`CLUB` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OFERTA_FECHA1`
    FOREIGN KEY (`FECHA_fecha`)
    REFERENCES `bgaribaldi709`.`FECHA` (`fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OFERTA_PERSONA1`
    FOREIGN KEY (`PERSONA_codigo`)
    REFERENCES `bgaribaldi709`.`PERSONA` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bgaribaldi709`.`COMPETICION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bgaribaldi709`.`COMPETICION` (
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bgaribaldi709`.`TEMPORADA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bgaribaldi709`.`TEMPORADA` (
  `codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bgaribaldi709`.`CLASIFICACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bgaribaldi709`.`CLASIFICACION` (
  `num_pos` INT NULL,
  `CLUB_nombre` INT NOT NULL,
  `COMPETICION_nombre` INT NOT NULL,
  `TEMPORADA_codigo` INT NOT NULL,
  PRIMARY KEY (`CLUB_nombre`, `COMPETICION_nombre`, `TEMPORADA_codigo`),
  INDEX `fk_CLASIFICACION_CLUB1_idx` (`CLUB_nombre` ASC) VISIBLE,
  INDEX `fk_CLASIFICACION_COMPETICION1_idx` (`COMPETICION_nombre` ASC) VISIBLE,
  INDEX `fk_CLASIFICACION_TEMPORADA1_idx` (`TEMPORADA_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_CLASIFICACION_CLUB1`
    FOREIGN KEY (`CLUB_nombre`)
    REFERENCES `bgaribaldi709`.`CLUB` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLASIFICACION_COMPETICION1`
    FOREIGN KEY (`COMPETICION_nombre`)
    REFERENCES `bgaribaldi709`.`COMPETICION` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLASIFICACION_TEMPORADA1`
    FOREIGN KEY (`TEMPORADA_codigo`)
    REFERENCES `bgaribaldi709`.`TEMPORADA` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bgaribaldi709`.`JUGADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bgaribaldi709`.`JUGADOR` (
  `peso` FLOAT NULL,
  `altura` FLOAT NULL,
  `PERSONA_codigo` INT NOT NULL,
  INDEX `fk_JUGADOR_PERSONA1_idx` (`PERSONA_codigo` ASC) VISIBLE,
  PRIMARY KEY (`PERSONA_codigo`),
  CONSTRAINT `fk_JUGADOR_PERSONA1`
    FOREIGN KEY (`PERSONA_codigo`)
    REFERENCES `bgaribaldi709`.`PERSONA` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bgaribaldi709`.`ENTRENADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bgaribaldi709`.`ENTRENADOR` (
  `fecha_inicio` INT NULL,
  `PERSONA_codigo` INT NOT NULL,
  INDEX `fk_ENTRENADOR_PERSONA1_idx` (`PERSONA_codigo` ASC) VISIBLE,
  PRIMARY KEY (`PERSONA_codigo`),
  CONSTRAINT `fk_ENTRENADOR_PERSONA1`
    FOREIGN KEY (`PERSONA_codigo`)
    REFERENCES `bgaribaldi709`.`PERSONA` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bgaribaldi709`.`ESPECIALIDAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bgaribaldi709`.`ESPECIALIDAD` (
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bgaribaldi709`.`ESPECIALIDAD_has_JUGADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bgaribaldi709`.`ESPECIALIDAD_has_JUGADOR` (
  `ESPECIALIDAD_nombre` VARCHAR(45) NOT NULL,
  `JUGADOR_PERSONA_codigo` INT NOT NULL,
  PRIMARY KEY (`ESPECIALIDAD_nombre`, `JUGADOR_PERSONA_codigo`),
  INDEX `fk_ESPECIALIDAD_has_JUGADOR_JUGADOR1_idx` (`JUGADOR_PERSONA_codigo` ASC) VISIBLE,
  INDEX `fk_ESPECIALIDAD_has_JUGADOR_ESPECIALIDAD1_idx` (`ESPECIALIDAD_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_ESPECIALIDAD_has_JUGADOR_ESPECIALIDAD1`
    FOREIGN KEY (`ESPECIALIDAD_nombre`)
    REFERENCES `bgaribaldi709`.`ESPECIALIDAD` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ESPECIALIDAD_has_JUGADOR_JUGADOR1`
    FOREIGN KEY (`JUGADOR_PERSONA_codigo`)
    REFERENCES `bgaribaldi709`.`JUGADOR` (`PERSONA_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
